### ISSUE TITLE
npm install vs npm link

### ISSUE THREAD

**Issue by steveoh** [agrc/kitchen-sink#10]
`npm install @agrc/layer-seletor@canary` functions properly when `npm link @agrc/layer-selector` causes a violation of hooks...

![image](https://user-images.githubusercontent.com/325813/72303917-1e1e8900-362c-11ea-8e4a-05659e41fb08.png)

the npm link creates a link to the `layer-selector` folder which contains the `dist` folder which is the same behavior as when npm installing.

`npm ls react` and `react-dom` both return the same version, `16.12.0`. I'm hearing that maybe the link command is bundling the same version twice because of bundling weirdness causing the error?

**Comment by steveoh** [comment]
![image](https://user-images.githubusercontent.com/325813/72369822-23c4af00-36be-11ea-874a-ea3169b06dd2.png)

**Comment by stdavis** [comment]
Is this still an issue?

**Comment by steveoh** [comment]
Probably

**Comment by steveoh** [comment]
Yes definitely still an issue
