### ISSUE TITLE
Header: Add UtahID auth functionality

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#256]
Add sign-in/out links with a logged-in status indicator.

**Comment by steveoh** [comment]
I'd like to implement this as a separate component with a companion context that can be placed inside the header.

The question then becomes do we make this work with firebase auth and utah id in the same component or would they be separate?

**Comment by stdavis** [comment]
Are there any instances where we use UtahID but not firebase? I can't think of any.

**Comment by steveoh** [comment]
We only use Utahid through firebase auth.

**Comment by steveoh** [comment]
I think we can close this.
