### ISSUE TITLE
Checkboxes look grainy/janky on some displays

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#276]
This is how they look on the HP monitors that are at TSOB.
![image](https://github.com/user-attachments/assets/46ff2f94-bc82-4c63-9532-e3c04b33db73)

They look good on my macbook screen:
<img width="268" alt="image" src="https://github.com/user-attachments/assets/11a7a486-bcd9-48bd-acb4-00c43fd71146">

**Comment by steveoh** [comment]
I'm ready to switch to a different icon library which will fix this issue and solve a few others at the same time.
