### ISSUE TITLE
Prop/Type Hints in VSCode

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#278]
I'm not getting any type/prop hints in VSCode which makes it hard to know what properties are available for a component.
![image](https://github.com/user-attachments/assets/5f404ff9-ee69-4ddb-aede-53a34b0a972e)

**Comment by steveoh** [comment]
Do you have any ideas how to improve the npm package to help with this? 

I'm seeing a "types" property is some other npm packages and then possibly an update to the exports for "." where you add an "import": { "types": ...}. They reference an index.d.ts file which i'm not sure we are generating?

I noticed they are including the source files which could help as well?

**Comment by stdavis** [comment]
I'm not sure. Although, I still think that it may be a good idea to publish just the source. I'm not sure why we are building these only for them to be run through a build system again in the app.
