### ISSUE TITLE
Built version of these packages can cause unit tests run in node to fail

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#338]
The build process for this project exports code that uses ESM imports without file extensions. This can cause issues when running the code in node such as via vitest. For example:

![image](https://github.com/user-attachments/assets/2fd71a53-4b89-4367-9828-da92201a9e3e)

![image](https://github.com/user-attachments/assets/9a1f1297-2e35-4591-b9be-1773e815853f)

[Here's an issue](https://github.com/nodejs/node/issues/46006) where the history can be viewed. It doesn't appear that Typescript or Node seem willing to fix the issue. I'm also not totally sure that it's not an issue with the Esri modules since there are other imports.

The workaround for vitest is to inline the packages from this repo:
```ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    server: {
      deps: {
        inline: ['@ugrc/utah-design-system'],
      },
    },
  },
});
```

**Comment by steveoh** [comment]
The esri docs do show imports esm with the `.js` extension. Is that a change we should make to solve the problem?

<img width="769" alt="image" src="https://github.com/user-attachments/assets/26d55fd3-e16d-436d-ac6d-c20c6c7589d2">

**Comment by steveoh** [comment]
I have some things to update in kitchen sink. I'll give it a try and we can test it in your project.

**Comment by stdavis** [comment]
This has been resolved by adding ".js" to the import paths.
