### ISSUE TITLE
Allow Sherlock input value to be controlled

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#340]
This would allow us to clear the input value from outside of the component. For example, I would like to clear the sherlock input when this clear button is clicked:
![image](https://github.com/user-attachments/assets/87b0b382-6ad5-4752-8c2d-3ef749484830)

**Comment by steveoh** [comment]
I have vague memories of us talking about this during development and there was something about nesting it in a form and maybe using a reset button?

**Comment by stdavis** [comment]
Yes, I think that this would be a similar use case, no?

**Comment by stdavis** [comment]
This was closed via the `context` param introduced in #368
