### ISSUE TITLE
Drawer (type=sidebar) Toggle Button Alignment

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#345]
When I fixed the gap between the sidebar and the main container in electrofishing, to be consistent with the other gaps, it made the toggle button offset in the wrong place:
![image](https://github.com/user-attachments/assets/edd449f2-e51d-4a70-b428-37fff3fa0d61)

**Comment by steveoh** [comment]
Yeah our drawer/tray implementation was very depending on the layout. Do you have any suggestions for correcting it?

**Comment by stdavis** [comment]
It looks like it's a problem in Atlas as well:
![image](https://github.com/user-attachments/assets/edab7f6a-f85f-465a-a04b-5a55ccf796e6)

The only thing that is different between this project and atlas is that I fixed the gap to the left of the map so that it matched everything else. I'm happy to make the same fix to atlas. Or maybe you think that it should stay?

The issues with the tray seem to be unrelated to the app layout to me.

**Comment by steveoh** [comment]
this was closed by #361
