### ISSUE TITLE
Button Sizes

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#346]
Is there any plan to add a size prop to Button? It would be nice to be able to make them smaller and bigger depending on the situation. For example, this "Download" button feels too large to me.
![image](https://github.com/user-attachments/assets/dba356dc-7206-4223-a57d-a8153a685f04)

Or maybe there's an easy way to do this that I'm missing?

**Comment by steveoh** [comment]
I think the plans are to add as we need. The UDS has rules for it so we can certainly add it.
