### ISSUE TITLE
Button Disabled State is confusing

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#353]
When a button is disabled, the background still changes when you hover over it. This is confusing because it looks very similar to an activated button. This is made worse because the [cursor doesn't change](https://github.com/agrc/kitchen-sink/issues/301) at all when it's over a disabled or non-disabled button.

Ref: https://designsystem.utah.gov/library/components/buttonsTags/button

**Comment by steveoh** [comment]
https://github.com/agrc/kitchen-sink/commit/2c2b01f944376451ca41da3249ce23cdbe6eef36
