### ISSUE TITLE
New Component: Map Activity Indicator

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#356]
Ref: https://github.com/agrc/electrofishing-query/pull/233

**Comment by steveoh** [comment]
The tailwind theme needed to be updated to add the animation for the new BusyBar component. Be sure to have at least version 1.1.0 which didn't publish with our pipeline :/

**Comment by stdavis** [comment]
Should the tailwind preset be added as a dependency of @ugrc/utah-design-system?

**Comment by steveoh** [comment]
I went back and forth on this. I don't think it does for the instances where you want a different theme or don't use the busy bar. What do you think?

**Comment by stdavis** [comment]
I can see both sides. I don't think that it would hurt to add it but I also don't think that it's a huge deal.
