### ISSUE TITLE
TextField: Allow for passing props to Input

### ISSUE THREAD

**Issue by stdavis** [agrc/kitchen-sink#396]
I would like to set some HTML props of the input element inside of the TextField component such as `spellCheck={false}`. I couldn't figure out a way to do this since no props are passed from TextField down to the Input component within it. Maybe adding a prop called `inputProps` would work?

**Comment by steveoh** [comment]
Try linking that branch and see how it works

**Comment by stdavis** [comment]
> What's the reason for disabling spellcheck?

I'm working on the address verification. When typing in addresses, there are lots of words that spellcheck doesn't like (e.g. "Holladay"). I just thought that it was annoying and wanted to turn it off. But I could also see wanting to add other props.

**Comment by steveoh** [comment]
I do like the idea of being able to forward props. some folks might like spellcheck but i'm indifferent with whatever you choose.
