### ISSUE TITLE
Upgrade Chalkdust

### ISSUE THREAD

**Issue by nathankota** [agrc/kitchen-sink#43]
> upgrade the chalkdust widget and system to react with the cloud

**Comment by steveoh** [comment]
### The Chalkdust system

1. A developer adds the `ChangeRequest` widget to a website
2. A user interacts with the component generating a web requests to the Send Email Service API
3. The Send Email Service would choose email addresses and a message template and send an email
4. The email contained a link to the [Chalkdust](https://github.com/agrc/Chalkdust/) viewer that would zoom to the point where the person created the issue and display the message

### Possible solutions 

- modernize the parts of the system, deploy to the cloud, and continue as we are. 
- use the arcgis platform with an editable feature service published in a web map, using web hooks to notify people.
- some combination of the two?

### Modernization Opportunities

- The ([ChangeRequest](https://github.com/agrc/agrc.ijit/blob/master/widgets/notify/ChangeRequest.js)) widget was built with dojo and would make a good custom react hook using render props.
- The send email service could become a cloud function

**Comment by steveoh** [comment]
tracked as a discussion in darwin https://github.com/agrc/darwin/discussions/6
